import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
    type: 'category',
    label: 'Philosophy',
    description: 'Why Pikku exists and the problems it solves',
    items: [{ dirName: 'philosophy', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'Core Features',
    description: 'Functions, middleware, sessions, and error handling',
    items: [{ dirName: 'core-features', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'Wiring',
    description: 'Connect your functions to different protocols',
    collapsible: true,
    collapsed: false,
    items: [
      {
        type: 'category',
        label: 'RPC',
        description: 'Function-to-function calls and external invocations',
        items: [{ dirName: 'rpcs', type: 'autogenerated' }]
      },
      {
        type: 'category',
        label: 'HTTP',
        description: 'REST APIs and Server-Sent Events',
        items: [{ dirName: 'http', type: 'autogenerated' }]
      }, {
        type: 'category',
        label: 'Channel',
        description: 'WebSocket real-time bidirectional communication',
        items: [{ dirName: 'channels', type: 'autogenerated' }]
      }, {
        type: 'category',
        label: 'Queue',
        description: 'Background job processing',
        items: [{ dirName: 'queue', type: 'autogenerated' }]
      },
      'scheduled-tasks',
      {
        type: 'category',
        label: 'Workflows',
        description: 'Multi-step processes with state management',
        items: [{ dirName: 'workflows', type: 'autogenerated' }]
      },
      {
        type: 'category',
        label: 'MCP',
        description: 'Model Context Protocol for AI agents',
        items: [{ dirName: 'mcp', type: 'autogenerated' }]
      },
      {
        type: 'category',
        label: 'CLI',
        description: 'Command-line interface tools',
        items: [{ dirName: 'cli', type: 'autogenerated' }]
      }
    ]
  }, 
  {
    type: 'category',
    label: 'Runtimes',
    description: 'Deploy to any platform without code changes',
    items: [
      {
        type: 'doc',
        id: 'runtimes/aws-lambda',
        label: 'AWS Lambda',
        customProps: {
          wirings: ['http', 'websocket', 'cron', 'queue']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/cloudflare-functions',
        label: 'Cloudflare Workers',
        customProps: {
          wirings: ['http', 'websocket', 'cron']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/express-middleware',
        label: 'Express Middleware',
        customProps: {
          wirings: ['http', 'websocket', 'sse', 'queue']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/fastify-plugin',
        label: 'Fastify Plugin',
        customProps: {
          wirings: ['http', 'websocket', 'sse', 'queue']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/nextjs-app',
        label: 'Next.js App',
        customProps: {
          wirings: ['http', 'sse']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/uws-handler',
        label: 'uWS Handler',
        customProps: {
          wirings: ['http', 'websocket', 'sse']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/ws-handler',
        label: 'WS Handler',
        customProps: {
          wirings: ['http', 'websocket']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/azure-functions',
        label: 'Azure Functions',
        customProps: {
          wirings: ['http', 'cron', 'queue']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/google-cloud-run-functions',
        label: 'Google Cloud Functions',
        customProps: {
          wirings: ['http', 'cron', 'queue']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/bullmq',
        label: 'BullMQ',
        customProps: {
          wirings: ['queue']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/pg-boss',
        label: 'PG Boss',
        customProps: {
          wirings: ['queue']
        }
      },
      {
        type: 'doc',
        id: 'runtimes/mcp-server',
        label: 'MCP Server',
        customProps: {
          wirings: ['mcp']
        }
      },
      {
        type: 'html',
        value: '<hr style="margin: 0.5rem 0;" />',
        defaultStyle: true
      },
      {
        type: 'category',
        label: 'Creating runtimes',
        description: 'Build custom adapters for any platform',
        items: [
          {
            type: 'doc',
            id: 'custom-runtimes/custom-http-runtime',
            label: 'Custom HTTP Runtime',
            customProps: {
              wirings: ['http']
            }
          },
          {
            type: 'doc',
            id: 'custom-runtimes/custom-websocket-handler',
            label: 'Custom WebSocket Handler',
            customProps: {
              wirings: ['websocket']
            }
          },
          {
            type: 'doc',
            id: 'custom-runtimes/custom-scheduler-handler',
            label: 'Custom Scheduler Handler',
            customProps: {
              wirings: ['cron']
            }
          },
          {
            type: 'doc',
            id: 'custom-runtimes/custom-queue-runtime',
            label: 'Custom Queue Runtime',
            customProps: {
              wirings: ['queue']
            }
          },
          {
            type: 'doc',
            id: 'custom-runtimes/custom-mcp-server',
            label: 'Custom MCP Server',
            customProps: {
              wirings: ['mcp']
            }
          }
        ]
      }
    ]
  },
  // {
  //   type: 'category',
  //   label: 'Middleware',
  //   items: [{ dirName: 'middleware', type: 'autogenerated' }]
  // }, 
  {
    type: 'category',
    label: 'API',
    description: 'Complete API reference documentation',
    items: [{ dirName: 'api', type: 'autogenerated' }]
  }],
  skills: [
    {
      type: 'autogenerated',
      dirName: 'skills'
    }
  ]
};

export default sidebars;