import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index', 
    {
    type: 'category',
    label: 'Concepts',
    items: [{ dirName: 'concepts', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'Core',
    items: [{ dirName: 'core', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'HTTP',
    items: [{ dirName: 'http', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'Channel',
    items: [{ dirName: 'channels', type: 'autogenerated' }]
  }, 
  'scheduled-tasks',
  {
    type: 'category',
    label: 'Runtimes',
    items: [{ dirName: 'runtimes', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'Custom Runtimes',
    items: [{ dirName: 'custom-runtimes', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'Comparisons',
    items: [{ dirName: 'comparison', type: 'autogenerated' }]
  }, {
    type: 'category',
    label: 'API',
    items: [{ dirName: 'api', type: 'autogenerated' }]
  }],
  guides: [
    'guides/yarn-workspaces'
  ]
};

export default sidebars;