name: Main
run-name: Publish to github pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out website repository
        uses: actions/checkout@v4

      - name: Check out pikku monorepo for skills
        uses: actions/checkout@v4
        with:
          repository: pikkujs/pikku
          path: pikku-repo

      - name: Debug - Check directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of pikku-repo:"
          ls -la pikku-repo || echo "pikku-repo not found"
          echo "Contents of pikku-repo/.claude:"
          ls -la pikku-repo/.claude || echo ".claude not found"
          echo "Contents of pikku-repo/.claude/skills:"
          ls -la pikku-repo/.claude/skills || echo "skills not found"

      - name: Sync skills from pikku repo
        run: ./sync-skills.sh pikku-repo/.claude/skills

      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: yarn build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/

  deploy:
    name: Deploy to github pages
    permissions:
      pages: write 
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4